# Modelling - building a recommendation engine

In [16]:
import pandas as pd
import numpy as np

import pickle 

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#Import Warnings
import warnings
warnings.filterwarnings("ignore")

## Load data

In [3]:
data = pickle.load(open("../Data/steam/alldata.pkl", 'rb'))

In [4]:
data.head()

,user_id,items_count,steam_id,user_url,items,id,publisher,genres,app_name,title,...,release_date,tags,discount_price,reviews_url,specs,price,early_access,developer,sentiment,metascore
0,76561197970982479,277,76561197970982480,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik...",10,Valve,[Action],Counter-Strike,Counter-Strike,...,2000-11-01,"[Action, FPS, Multiplayer, Shooter, Classic, T...",NaN,http://steamcommunity.com/app/10/reviews/?brow...,"[Multi-player, Valve Anti-Cheat enabled]",9.99,False,Valve,Overwhelmingly Positive,88
1,js41637,888,76561198035864384,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik...",10,Valve,[Action],Counter-Strike,Counter-Strike,...,2000-11-01,"[Action, FPS, Multiplayer, Shooter, Classic, T...",NaN,http://steamcommunity.com/app/10/reviews/?brow...,"[Multi-player, Valve Anti-Cheat enabled]",9.99,False,Valve,Overwhelmingly Positive,88
2,Riot-Punch,328,76561197963445856,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik...",10,Valve,[Action],Counter-Strike,Counter-Strike,...,2000-11-01,"[Action, FPS, Multiplayer, Shooter, Classic, T...",NaN,http://steamcommunity.com/app/10/reviews/?brow...,"[Multi-player, Valve Anti-Cheat enabled]",9.99,False,Valve,Overwhelmingly Positive,88
3,doctr,541,76561198002099488,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea...",10,Valve,[Action],Counter-Strike,Counter-Strike,...,2000-11-01,"[Action, FPS, Multiplayer, Shooter, Classic, T...",NaN,http://steamcommunity.com/app/10/reviews/?brow...,"[Multi-player, Valve Anti-Cheat enabled]",9.99,False,Valve,Overwhelmingly Positive,88
4,corrupted_soul,115,76561198007659920,http://steamcommunity.com/id/corrupted_soul,"[{'item_id': '4000', 'item_name': 'Garry's Mod...",10,Valve,[Action],Counter-Strike,Counter-Strike,...,2000-11-01,"[Action, FPS, Multiplayer, Shooter, Classic, T...",NaN,http://steamcommunity.com/app/10/reviews/?brow...,"[Multi-player, Valve Anti-Cheat enabled]",9.99,False,Valve,Overwhelmingly Positive,88

In [11]:
# Get relevant columns
recdata = data[['steam_id', 'id']]

In [12]:
recdata.head()

            steam_id  id
0  76561197970982480  10
1  76561198035864384  10
2  76561197963445856  10
3  76561198002099488  10
4  76561198007659920  10

In [13]:
# Add binary owned column
recdata['owned'] = np.ones(shape = recdata.shape[0])
recdata.head()

/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

            steam_id  id  owned
0  76561197970982480  10    1.0
1  76561198035864384  10    1.0
2  76561197963445856  10    1.0
3  76561198002099488  10    1.0
4  76561198007659920  10    1.0

In [15]:
# Save using pickle
pickle.dump(recdata, open('recdata.pkl','wb'))

In [17]:
# Pivot table
user_id = recdata.pivot_table(index = ['steam_id'], columns = ['id'], values = 'owned')
user_id.head()

id,10,20,30,40,50,60,70,80,130,220,...,527440,527510,527520,527810,527890,527900,528580,528660,529820,530720
steam_id,,,,,,,,,,,,,,,,,,,,,
76561197960269200,1.0,1.0,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76561197960270496,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76561197960270736,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76561197960271616,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76561197960271888,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN